### ISSUE TITLE
Last known value cache

### ISSUE THREAD

**Issue by einarlove** [unfold/react-firebase#10]
```js
cache: Boolean / <Object with get/set/remove/clear aka Map>

const lastValue = cache.get(pathWithQueryHash)

if (lastValue) {
 callback(lastValue) 
}

ref.on('value', snapshot => {
  const value = snapshot.val()

  cache.set(pathWithQueryHash, value)

  if (cache.length > cacheMaxSize) {
    cache.remove
  }

  callback(value)
})


this.cache = options.cache && ( context.cache || new Map())

const MyComponent = connect({ cache: true })(DerpComponent)
```

**Comment by simenbrekken** [comment]
I'm starting to think caching should be done by means of composition:

`cacheProps(connect(MyComponent))`

1. `connect`'ed Component is mounted
2. Subscriptions are resolved and props propagated to `WrappedComponent`
3. `connect`'ed Component is unmounted
4. Subscriptions are cleared
5. `connect`'ed Component is mounted
6. `cacheProps`'ed component receives computed cached props:

```js
const props = lodash.mapValues(cachedProps, (key, cachedValue) => {
  const value = this.props[key]

  return value == null ? value : cachedValue
}
```

**Comment by simenbrekken** [comment]
Closing this until an issue targeting this is reported. My previous comment should be enough to get started.
