### ISSUE TITLE
Synchronize published version with repo sources

### ISSUE THREAD

**Issue by akofman** [unfold/react-firebase#21]
Hello,

Thanks for this really convenient HOC.
It looks like the version from `npm` is not exactly the same than from this repo. The version from `npm` indicates `2.0.2`, the one from the repo is still `2.0.1`and I can't get it work properly actually :/

**Comment by simenbrekken** [comment]
@akofman Seems the `2.0.2` version got lost in transition between computers, I'll be sure to bump it to `2.0.3` once I merge #22

**Comment by akofman** [comment]
Haha no pb :+1:

**Comment by simenbrekken** [comment]
Closed with #22
