### ISSUE TITLE
Rename `connect` HoC

### ISSUE THREAD

**Issue by simenbrekken** [unfold/react-firebase#26]
While the name is generic it might collide with `redux` and for people coming from `redux` it might be confusing. In `@unfold/fetch-data` we're more wisely IMHO using the name [`connectFetchData`](https://github.com/unfold/fetch-data/blob/master/src/index.js#L3)

**Comment by simenbrekken** [comment]
@einarlove How about `withFirebase` or something similar in the spirit of Recompose and Apollo?

**Comment by einarlove** [comment]
Well `withRouter` or `withTheme` Takes no arguments and passes one prop from context. So `withFirebase` confuses me.

**Comment by einarlove** [comment]
I'm :+1: for `connectFirebase`, but would wait with it since it's a breaking change

**Comment by einarlove** [comment]
Unless
```
export connect from './conmectFirebase'
export connectFirebase from './conmectFirebase'
```
