### ISSUE TITLE
Fix examples

### ISSUE THREAD

**Issue by einarlove** [unfold/react-firebase#31]
Now that webpack is upgraded to v2, examples does not work anymore

- [ ] Include `-loader` in webpack.config loaders
- [ ] `Uncaught ReferenceError: webpackJsonp is not defined`

**Comment by simenbrekken** [comment]
@einarlove I assume this was obsoleted in #40?

**Comment by einarlove** [comment]
Believe so

On Sun, May 28, 2017 at 20:31, Simen Brekken <notifications@github.com> wrote:
@einarlove [https://github.com/einarlove] I assume this was obsoleted in #40 [https://github.com/unfold/react-firebase/pull/40] ?
