### ISSUE TITLE
Error using auth(): Cannot read property '_getService' of undefined

### ISSUE THREAD

**Issue by enthal** [unfold/react-firebase#45]
per `connect((props, ref, { auth }) => auth())(SomeComponent)` (simplified)

Error: **TypeError: Cannot read property '_getService' of undefined** 
in call to `auth()`.

That's from the actual Firebase code:
```
FirebaseAppImpl.(anonymous function)
node_modules/firebase/app/firebase_app.js:288
  285 | namespace[name] = serviceNamespace;
  286 | // Patch the FirebaseAppImpl prototype
  287 | FirebaseAppImpl.prototype[name] = function () {
> 288 |     var serviceFxn = this._getService.bind(this, name);
  289 | 
  290 |     for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
  291 |         args[_key] = arguments[_key];
```

This happens no matter where I try to call `auth` when closed over in the `connect` callback.

The `auth` function is not properly bound.  

# Workaround 
_departing from the example in the README_:
```
connect((props, ref, firebase) => firebase.auth())(SomeComponent)
```

# PS
Thanks!  Loving this package!

**Comment by einarlove** [comment]
Ah! thanks for spotting it!

**Comment by MerryOscar** [comment]
Hi,

I'm getting the same error but not using the react-firebase project and was wondering if anyone could point me in the right direction.

I'm trying to implement [Firebase Phone Number Auth](https://firebase.google.com/docs/auth/web/phone-auth) but when I try and create the ReCaptcha object I get the same error as above:

```javascript
  componentDidMount() {
      this.recaptchaVerifier = new Firebase.auth().RecaptchaVerifier('recaptcha-container');
  }
```

```
error TypeError: Cannot read property 'bind' of undefined at new FirebaseAppImpl.(anonymous function)
```
which is triggered at line 305 of firebaseApp.js 
```
var serviceFxn = this._getService.bind(this, name);
```

Would anyone be able to suggest the right way to ensure that the `auth` function is properly bound in this case?

Thanks!

**Comment by einarlove** [comment]
Hard to say. `auth()` is a method of a firebaseApp, so the `new Firebase.auth()` is new to me. If this is not related to react-firebase, you should open a issue on [firebase/firebase-js-sdk](https://github.com/firebase/firebase-js-sdk)

**Comment by simenbrekken** [comment]
@MerryOscar While quite confusing, that's actually a typo on your part. It should read: 
```
componentDidMount() {
  this.recaptchaVerifier = new Firebase.auth.RecaptchaVerifier('recaptcha-container')
}
```

Notice how `RecaptchaVerifier` is a static property of `auth` not an `auth` instance.

**Comment by MerryOscar** [comment]
@simenbrekken thanks for this yes you're right I was getting very confused and trying to create the RecaptchaVerifier on the already initialised FirebaseApp rather than the actual module. It's working fine with the code above.

Also thanks for the tip on using a ref instead of global ID! :)
