### ISSUE TITLE
firebaseApp does not update if you change it in Provider or as prop

### ISSUE THREAD

**Issue by einarlove** [unfold/react-firebase#47]
The firebaseApp is set in the FirebaseConnect constructor, making it imposible to change it with a prop or with Provider via context

One solution is to create a getter:
```js
getFirebaseApp() {
  return this.props.firebaseApp || this.context.firebaseApp || firebase.app()
}
``` 

or update `this.firebaseApp` in `componentWillReceiveProps`. Not sure if it will update on context change tho.

**Comment by simenbrekken** [comment]
I'm considering this an edge-case that can be solved by using 

```js
<Provider firebaseApp={firebaseApp} key={firebaseApp.name}>
```
