### ISSUE TITLE
Firebase 3.x.x

### ISSUE THREAD

**Issue by kibin** [unfold/react-firebase#5]
What are your plans on upgrading to firebase 3.x.x? Do you need any help with that?

I’m now starting to build an app with this library and will try to use it with latest version of firebase api. If I run into any troubles, I think that I will update the library code to work with current api. Should I make a PR in this case?

**Comment by prescottprue** [comment]
Myself and others have been implementing this within a few other libraries, but were hoping to combine them all into one.

Not sure if you are on the [Firebase Slack](firebase-community.slack.com), but there is a Redux channel there. Might be good to have discussion there so we don't have to leave an issue open on your repo.

**Comment by einarlove** [comment]
You're welcome to submit a PR @kibin ❤️

**Comment by prescottprue** [comment]
I've been working on [redux-firebasev3](https://github.com/prescottprue/redux-firebasev3) to have v3 capabilities. It wasn't too hard to convert code over to work with v3, @kibin have you started doing it at all with this library?

**Comment by simenbrekken** [comment]
I've started the work on upgrading to v3 in #6

**Comment by simenbrekken** [comment]
Closed by #6
