### ISSUE TITLE
Access of auth namespace?

### ISSUE THREAD

**Issue by mbbender** [unfold/react-firebase#54]
I'm attempting to use the authentication provider and using it for email/password seems to work fine using `firebase.auth().signInWithEmailAndPassword()` in the connect function. But in trying to go through the examples and do a google auth login I have a `googleAuth: firebase.auth().signInWithPopup` in my connect function. Per the examples it looks like I need to call that function with a `new firebase.auth.GoogleAuthProvider()` I assumed that wouldn't require an initialized app to instantiate but I've tried both ways with no luck. I've tried to add an `auth: firebase.auth()` to my props via the connection function and call a `new auth.GoogleAuthProvider()` in my Login with google function in my component. I've also tried to just import firebase and do a `new firebase.auth.GoogleAuthProvider()`.... neither work. Any suggestions on how to get this to work?

**Comment by einarlove** [comment]
React-firebase does not meddle with authentication or storage. Its only concern is connecting to the database.

Unfamiliar with the google auth provider so can't help you. Check stackoverflow and the firebase docs.

**Comment by mbbender** [comment]
Ok, you have an example with the todo app

```javascript
login: (email, password) => firebase.auth().signInWithEmailAndPassword(email, password)
```

That made me think it was an attempt to integrate with all of firebase services. This is just for the realtime database?

**Comment by einarlove** [comment]
It was an example how you could create actions as props and use the firebase app or reference as you would otherwise.
