### ISSUE TITLE
multiple errors on codepen 

### ISSUE THREAD

**Issue by seanburlington** [unfold/react-firebase#57]
https://codepen.io/einarlove/pen/peoMbp?editors=1010

Starts with 

The resource from “https://unpkg.com/react@16.13.1/dist/react.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).

But multiple errors logged 

All commits look old - is this project still alive ?

**Comment by einarlove** [comment]
No, this project is not maintained anymore. The React team is going to introduce a data loading library for services such as Firebase soon.

If you want to fix these errors or maintain this project, let me know.

**Comment by mastef** [comment]
> The React team is going to introduce a data loading library for services such as Firebase soon.

hi @einarlove do you have more info on this approach?

**Comment by einarlove** [comment]
i have on good authority that it will come alongside Suspense, not sooner. Theres nothing more of interest I can share.
